# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

kuka_arm_0_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_0_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_1_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_1_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_2_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_2_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_3_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_3_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_4_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_4_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_5_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_5_joint
  pid: {p: 10000, i: 1.0, d: 10.0}

kuka_arm_6_joint_controller:
  type: effort_controllers/JointPositionController
  joint: kuka_arm_6_joint
  pid: {p: 10000, i: 1.0, d: 10.0}
