controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [kuka_arm_0_joint,kuka_arm_1_joint,kuka_arm_2_joint,kuka_arm_3_joint,kuka_arm_4_joint,kuka_arm_5_joint,kuka_arm_6_joint]
