# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kuka_arm_0_joint
    - kuka_arm_1_joint
    - kuka_arm_2_joint
    - kuka_arm_3_joint
    - kuka_arm_4_joint
    - kuka_arm_5_joint
    - kuka_arm_6_joint
  gains: # Required because we're controlling an effort interface
    kuka_arm_0_joint: {p: 20000000000.0,  d: 0, i: 100.0}
    kuka_arm_1_joint: {p: 20000000000.0,  d: 10, i: 100.0}
    kuka_arm_2_joint: {p: 20000000000.0,  d: 0, i: 100.0}
    kuka_arm_3_joint: {p: 20000000000.0,  d: 0, i: 100.0}
    kuka_arm_4_joint: {p: 20000000000.0,  d: 0, i: 100.0}
    kuka_arm_5_joint: {p: 20000000000.0,  d: 0, i: 100.0}
    kuka_arm_6_joint: {p: 20000000000.0,  d: 0, i: 100.0}

  constraints:
    goal_time: 0.2
    kuka_arm_0_joint:
      goal: 0.1
      trajectory: 0.2
    kuka_arm_1_joint:
      goal: 0.2
      trajectory: 0.2
    kuka_arm_2_joint:
      goal: 0.2
      trajectory: 0.2
    kuka_arm_3_joint:
      goal: 0.2
      trajectory: 0.2
    kuka_arm_4_joint:
      goal: 0.2
      trajectory: 0.2
    kuka_arm_5_joint:
      goal: 0.2
      trajectory: 0.2
    kuka_arm_6_joint:
      goal: 0.2
      trajectory: 0.2

# gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - left_finger
#     - right_finger
#   gains:
#     left_finger: {p: 100.0,  d: 1.0, i: 0.0}
#     right_finger: {p: 100.0,  d: 1.0, i: 0.0}
