# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains: # Required because we're controlling an effort interface
    panda_joint1: {p: 1000000.0,  d: 1.0, i: 5.0}
    panda_joint2: {p: 1000000.0,  d: 1.0, i: 10.0}
    panda_joint3: {p: 1000000.0,  d: 1.0, i: 10.0}
    panda_joint4: {p: 1000000.0,  d: 1.0, i: 3.0}
    panda_joint5: {p: 1000000.0,  d: 0.1, i: 1.0}
    panda_joint6: {p: 1000000.0,  d: 0.1, i: 1.0}
    panda_joint7: {p: 1000000.0,  d: 0.1, i: 1.0}

  constraints:
    goal_time: 0.2
    panda_joint1:
      goal: 0.1
      trajectory: 0.2
    panda_joint2:
      goal: 0.2
      trajectory: 0.2
    panda_joint3:
      goal: 0.2
      trajectory: 0.2
    panda_joint4:
      goal: 0.2
      trajectory: 0.2
    panda_joint5:
      goal: 0.2
      trajectory: 0.2
    panda_joint6:
      goal: 0.2
      trajectory: 0.2
    panda_joint7:
      goal: 0.2
      trajectory: 0.2

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    - panda_finger_joint2
  gains:
    panda_finger_joint1: {p: 100.0,  d: 1.0, i: 0.0}
    panda_finger_joint2: {p: 100.0,  d: 1.0, i: 0.0}
